// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqr9zMJ676Z2KYB8SYVkcn5J8KGlIEkfQ',
    appId: '1:584582121487:web:3eb1e5523121b11865bb7a',
    messagingSenderId: '584582121487',
    projectId: 'aplikasi-rental-ps',
    authDomain: 'aplikasi-rental-ps.firebaseapp.com',
    storageBucket: 'aplikasi-rental-ps.appspot.com',
    measurementId: 'G-TFE7GEJ4RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDOQxnlEdSGwMJEjVuSvyDow-Lk4tUiI',
    appId: '1:584582121487:android:558d8bcc42640c9265bb7a',
    messagingSenderId: '584582121487',
    projectId: 'aplikasi-rental-ps',
    storageBucket: 'aplikasi-rental-ps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZOq5U4yQfvkZvoBDHScoxW4Xp3zAwC9w',
    appId: '1:584582121487:ios:a1e232b223cefe6b65bb7a',
    messagingSenderId: '584582121487',
    projectId: 'aplikasi-rental-ps',
    storageBucket: 'aplikasi-rental-ps.appspot.com',
    iosBundleId: 'com.example.aplikasirentalPs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZOq5U4yQfvkZvoBDHScoxW4Xp3zAwC9w',
    appId: '1:584582121487:ios:a1e232b223cefe6b65bb7a',
    messagingSenderId: '584582121487',
    projectId: 'aplikasi-rental-ps',
    storageBucket: 'aplikasi-rental-ps.appspot.com',
    iosBundleId: 'com.example.aplikasirentalPs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqr9zMJ676Z2KYB8SYVkcn5J8KGlIEkfQ',
    appId: '1:584582121487:web:51584f49cbac50f665bb7a',
    messagingSenderId: '584582121487',
    projectId: 'aplikasi-rental-ps',
    authDomain: 'aplikasi-rental-ps.firebaseapp.com',
    storageBucket: 'aplikasi-rental-ps.appspot.com',
    measurementId: 'G-JTJCKZ6Q40',
  );
}
